version: '3.8'
services:
  app:
    build:
      context: ./
      args:
        - SPRING_PROFILE=dev
#    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    ports:
      - "8080:8080"  # Spring Boot 애플리케이션 포트 매핑
    depends_on:
      - mysql
      - redis
    environment:
      - DEV_DB_URL=jdbc:mysql://mysql:3306/hanghae
      - DEV_DB_USERNAME=root
      - DEV_DB_PASSWORD=password
      - DEV_REDIS_HOST=redis

  mysql:
    image: mysql:8.0  # MySQL 이미지 버전
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=hanghae
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    restart: always

  redis:
    image: redis:latest  # Redis 이미지 버전
    ports:
      - "6379:6379"

volumes:
  mysql-data:
