on:
  push:
    branches:
      - develop

env:
  SERVICE_NAME: hanghae-plus-3
  SPRING_PROFILE: dev
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      ## gradlew 의 권한을 줍니다.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew clean build --debug

      ## 이미지 태그에 시간 설정을 하기 위해서 현재 시간을 가져옵니다.
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH:mm:ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"

      ## AWS login
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      ## 도커 이미지 빌드 후 ECR로 푸시합니다. (AWS ECR에서 확인 가능합니다.)
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker build --build-arg="SPRING_PROFILE=${{ env.SPRING_PROFILE }}" -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy-ecs:
    needs: build-and-push-ecr
    runs-on: ubuntu-latest

    steps:
      ## 다시 로그인
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      ## 여기서 기존 task-definition 파일을 가져와 새로운 task-definition 파일을 생성합니다.
#      - name: Retrieve most recent ECS task definition JSON file
#        id: retrieve-task-def
#        run: |
#          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION }} --query taskDefinition | jq -r 'del(
#            .taskDefinitionArn,
#            .requiresAttributes,
#            .compatibilities,
#            .revision,
#            .status,
#            .registeredAt,
#            .registeredBy
#          )' > task-definition.json
#          cat task-definition.json
#          echo "task-def-file=task-definition.json" >> $GITHUB_OUTPUT

      ## 여기서 task-definition 파일에 새로운 도커 이미지를 추가합니다.
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
#          task-definition: ${{ steps.retrieve-task-def.outputs.task-def-file }}
          task-definition: task-definition.json
          container-name: hhplus-dev
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      ## ECS로 배포합니다.
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: hhplus-dev
          cluster: cluster-hhplus-dev
          wait-for-service-stability: true