on:
  pull_request:
    branches:
      - develop

env:
  DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
  DEV_DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
  DEV_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      ## gradlew 의 권한을 줍니다.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew clean build --debug
